/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author M.A.S tech
 */
public class Buy extends javax.swing.JFrame {
 private final String url = "jdbc:sqlserver://localhost\\SQL2018;databaseName=pharmacy;user=sa;password=12345;";

    /**
     * Creates new form Buy
     */
    public Buy() 
    {
        initComponents();
        setVisible(true);
    }

    public Buy(String m_name)
    {
        initComponents();
        setVisible(true);
        setLocation(350, 250);
       jLabelshow.setText(m_name);
       setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
       setResizable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabelshow = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 140, 60, 30);

        jTextField2.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(10, 110, 80, 21);

        jLabelshow.setFont(new java.awt.Font("OCR A Extended", 3, 24)); // NOI18N
        jLabelshow.setForeground(new java.awt.Color(0, 0, 102));
        jLabelshow.setText("jLabel3");
        jPanel1.add(jLabelshow);
        jLabelshow.setBounds(240, 10, 210, 30);

        jLabel2.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("amount");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 53, 15);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/cart.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, -30, 410, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int Subtract (int Amount1,int Amount2)
{
  return Amount1 - Amount2;
}

public static float Multiply (float price,int Amount)
{
  return price*Amount;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String name =search_page.SearchTextField.getText();
        jLabelshow.setText(name);
        //System.err.println("ww");
        
        String am =jTextField2.getText();
        int amount = 0;
        try 
        {
           amount= Integer.parseInt(am);
            
        }
        catch (NumberFormatException e)
       {
           JOptionPane.showMessageDialog(this,"Please Enter a valid amount ");
          return;
       }
        
        int Amount = 0;
        float price = 0;
        if(am.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter amount Of Medicine");
            return;
        }
        if(amount <=0){
            JOptionPane.showMessageDialog(this, "Please Enter a true value !!");
            return;
           
        }
        
         
        
      
Connection con = null;
        Statement comand=null;
        ResultSet rst =null;
        try {

            con= DriverManager.getConnection(url);
            comand = con.createStatement();
            
          String a="select * from medicine "+"WHERE m_name='"+name+"'";
          rst = comand.executeQuery(a);
          
           if(rst.next())
            {
                Amount = rst.getInt("amount");
                price = rst.getFloat("price");
                if(amount>Amount)
                {
                  JOptionPane.showMessageDialog(this,"sorry this Amount not avillable now !!");
                  return;
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid medicine name");
            }
         String sql = ("UPDATE medicine set amount="+Subtract(Amount,amount)+"WHERE m_name='"+name+"'") ;
         
                int affectsRows = comand.executeUpdate(sql);
            if(affectsRows == 1)
            {
                JOptionPane.showMessageDialog(this, "Purchase successful .. \n "
                        + " You must pay the Price :  "+Multiply(price,amount)+" L.E  "
                        + " you will pay cash on delivery \n "
                        + " thank you for using this service \n");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Incorrect Amount !!!");
            }

            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
           // if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabelshow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
