/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author M.A.S tech
 */
public class GUI extends javax.swing.JFrame {
int amount;
    /**
     * Creates new form GUI
     */
 private final String url = "jdbc:sqlserver://localhost\\SQL2018;databaseName=pharmacy;user=sa;password=12345;";

    public GUI() {
        initComponents();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, "Cannot load JDBC Driver!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTelephon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Registration"));
        jPanel6.setForeground(new java.awt.Color(255, 0, 51));
        jPanel6.setToolTipText("");
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel1.setText("First name");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(150, 180, 110, 40);

        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldFname);
        jTextFieldFname.setBounds(250, 190, 60, 20);

        jLabel2.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel2.setText("Last name");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(320, 190, 90, 19);

        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldLname);
        jTextFieldLname.setBounds(420, 190, 60, 20);

        jLabel3.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel3.setText("User name");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(180, 261, 90, 30);

        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldUserName);
        jTextFieldUserName.setBounds(280, 270, 60, 20);

        jLabel4.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel4.setText("E-Mail");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(510, 270, 52, 19);
        jPanel6.add(jTextFieldMail);
        jTextFieldMail.setBounds(580, 270, 60, 20);

        jLabel5.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(350, 270, 90, 19);
        jPanel6.add(jPasswordField1);
        jPasswordField1.setBounds(440, 270, 60, 20);

        jLabel7.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel7.setText("Telephon");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(640, 190, 90, 19);
        jPanel6.add(jTextFieldTelephon);
        jTextFieldTelephon.setBounds(730, 190, 60, 20);

        jLabel8.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel8.setText("Address");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(490, 190, 72, 19);
        jPanel6.add(jTextFieldAddress);
        jTextFieldAddress.setBounds(570, 190, 60, 20);

        jButton1.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(340, 330, 130, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon("F:\\Pharmacy system (3) (1)\\Pharmacy system (3)\\Pharmacy system\\src\\pharmacy\\pharmacy-backdrop-clipart-free-18.jpg")); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(0, 0, 800, 430);

        jTabbedPane1.addTab("Registration", jPanel6);
        jPanel6.getAccessibleContext().setAccessibleName("Regesration Form");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel7.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Axure Handwriting", 3, 24)); // NOI18N
        jLabel6.setText("User name");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(44, 65, 150, 25);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField1);
        jTextField1.setBounds(190, 70, 197, 20);

        jLabel10.setFont(new java.awt.Font("Axure Handwriting", 3, 24)); // NOI18N
        jLabel10.setText("Password");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(60, 150, 120, 25);
        jPanel7.add(jPasswordField2);
        jPasswordField2.setBounds(190, 150, 197, 20);

        jButton2.setFont(new java.awt.Font("Axure Handwriting", 3, 24)); // NOI18N
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(200, 220, 170, 33);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("هذا المشروع قيد التطوير");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(20, 410, 170, 14);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/f974cd6614b64a9fc37a96e7_rw_1920.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(-480, 0, 1260, 670);

        jTabbedPane1.addTab("Login", jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Information"));
        jPanel8.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Axure Handwriting", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("user name");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(40, 10, 140, 40);
        jPanel8.add(usernameTextField);
        usernameTextField.setBounds(10, 50, 190, 33);

        jLabel11.setFont(new java.awt.Font("Axure Handwriting", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("password");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(40, 100, 140, 24);

        login_btn.setFont(new java.awt.Font("Axure Handwriting", 3, 24)); // NOI18N
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel8.add(login_btn);
        login_btn.setBounds(20, 190, 170, 40);
        jPanel8.add(jPasswordField3);
        jPasswordField3.setBounds(10, 130, 190, 31);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/1501231493928_1.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(0, 0, 810, 430);

        jTabbedPane1.addTab("Employee Login", jPanel8);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Names"));

        jLabel16.setFont(new java.awt.Font("Axure Handwriting", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Osama Gamal      [15-00532 ]");

        jLabel18.setFont(new java.awt.Font("Axure Handwriting", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setText("Ahmed Sami        [16-00170 ]");

        jLabel19.setFont(new java.awt.Font("Axure Handwriting", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setText("Mahmoud Omar   [16-00229 ]");

        jLabel20.setFont(new java.awt.Font("Axure Handwriting", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 255));
        jLabel20.setText("Abanoub Kromer [13-00662 ]");

        jLabel21.setFont(new java.awt.Font("Axure Handwriting", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 255));
        jLabel21.setText("Mohamed said     [16-00018 ]");

        jLabel22.setFont(new java.awt.Font("Axure Handwriting", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 255));
        jLabel22.setText("Maichel kamal      [ 15-00535 ]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pharmacy Group", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About us", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Home");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Fname = jTextFieldFname.getText();
        String Lname = jTextFieldLname.getText();
        String Tel = jTextFieldTelephon.getText();
        String UserName = jTextFieldUserName.getText();
        String Mail = jTextFieldMail.getText();
        String Address = jTextFieldAddress.getText();
        String password = jPasswordField1.getText();
        if (Fname.isEmpty()||Lname.isEmpty()||Tel.isEmpty()||UserName.isEmpty()
            ||Mail.isEmpty()||Address.isEmpty()||password.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter all your data");
            return;
        }
        try 
        {
            Integer.parseInt(Tel);
        }
        catch (Exception e)
       {
           JOptionPane.showMessageDialog(this,"Please Ented a valid telephon number");
           return;
       }
        
        
        {
        
        }
        Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand = con.createStatement();
            String sql="select * from customer where Uname ='"+UserName+"'";
            rst =comand.executeQuery(sql);
            if(rst.next())
            JOptionPane.showMessageDialog(this, "this username is already Accessed");
            else
            {
                sql = "Insert into customer(Fname,Lname,Tel,Uname,password,address,mail)"
                + " values('" + Fname
                + "','" + Lname
                + "','" + Tel
                + "','" + UserName
                + "','" + password
                + "','" + Address
                + "','" + Mail+ "')";
                comand.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Done ..");
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed

        // TODO add your handling code here:
        String name=usernameTextField.getText();
        String password=jPasswordField3.getText();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your username");
            return;
        }
        if(password.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your password");
            return;
        }
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        try
        {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "select * from employees where name='"+name+"' "
            + "and password='"+password+"'";
            result = stmt.executeQuery(query);
            
            String job_role = null;
            
       
            if(result.next())
            {
                
               job_role= result.getString("job_role"); 
                if(job_role.equals("pharmacist"))
                {
                    pharmacist ph=new pharmacist();
                }
                
                if(job_role.equals("data_entry"))
                {
                    Data_Entry DE=new Data_Entry();
                }
                
                if(job_role.equals("Manager"))
                
                {
                   Manager M=new Manager();
                }

            }
            
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Username or password");
            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        finally
        {
            if(con != null){ try{ con.close();} catch(Exception ex){}}
            if(stmt != null){ try{ stmt.close();} catch(Exception ex){}}
            if(result != null){ try{ result.close();} catch(Exception ex){}}
        }
    }//GEN-LAST:event_login_btnActionPerformed
    public boolean Check_Login(String user_name,String password)
    {
        
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        boolean flag = false;
        try
        {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "select * from customer where Uname='"+user_name+"' "
            + "and password='"+password+"'";
            result = stmt.executeQuery(query);
            String fname = null;
            String lname = null;

            if(result.next())
            {
                fname = result.getString("Fname");
                lname = result.getString("Lname");

                search_page cl = new search_page(fname,lname);
                flag = true;
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Username or password");
                flag = false;
            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        finally
        {
            if(con != null){ try{ con.close();} catch(Exception ex){}}
            if(stmt != null){ try{ stmt.close();} catch(Exception ex){}}
            if(result != null){ try{ result.close();} catch(Exception ex){}}
        }
        return flag;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String username = jTextField1.getText();
        String password = jPasswordField2.getText();

        if(username.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your username");
            return;
        }
        if(password.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your password");
            return;
        }
        
        Check_Login(username, password);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldTelephon;
    private javax.swing.JTextField jTextFieldUserName;
    private javax.swing.JButton login_btn;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
