/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import javax.swing.*;
import java.sql.*;

/**
 *
 * @author M.A.S tech
 */
public class Manager extends javax.swing.JFrame {
 private final String url = "jdbc:sqlserver://localhost\\SQL2018;databaseName=pharmacy;user=sa;password=12345;";

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        setVisible(true);
        setLocation(250, 200);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        setResizable(false);
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        }catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this,"Cannot Load JDBC Driver !!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name_textfield = new javax.swing.JTextField();
        price_textfield = new javax.swing.JTextField();
        amount_textfield = new javax.swing.JTextField();
        notes_textfield = new javax.swing.JTextField();
        done_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        name_textfield1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        price_textfield1 = new javax.swing.JTextField();
        name_textfield2 = new javax.swing.JTextField();
        amount_textfield1 = new javax.swing.JTextField();
        notes_textfield1 = new javax.swing.JTextField();
        done_btn2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jButtonsearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N

        jPanel8.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel1.setText("name");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(10, 46, 48, 26);

        jLabel2.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel2.setText("price");
        jPanel8.add(jLabel2);
        jLabel2.setBounds(10, 106, 48, 25);

        jLabel3.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel3.setText("amount");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(10, 162, 53, 26);

        jLabel4.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel4.setText("notes");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(10, 202, 37, 24);
        jPanel8.add(name_textfield);
        name_textfield.setBounds(81, 49, 150, 35);
        jPanel8.add(price_textfield);
        price_textfield.setBounds(81, 102, 150, 32);
        jPanel8.add(amount_textfield);
        amount_textfield.setBounds(81, 160, 151, 31);

        notes_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notes_textfieldActionPerformed(evt);
            }
        });
        jPanel8.add(notes_textfield);
        notes_textfield.setBounds(81, 207, 154, 32);

        done_btn.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        done_btn.setText("done");
        done_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_btnActionPerformed(evt);
            }
        });
        jPanel8.add(done_btn);
        done_btn.setBounds(188, 290, 75, 27);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vector-pharmacy.jpg"))); // NOI18N
        jLabel15.setText("jLabel11");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(-30, -10, 980, 340);

        jTabbedPane2.addTab("Add Medicine", jPanel8);

        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel5.setText("Medicine Name");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(121, 62, 142, 24);
        jPanel3.add(name_textfield1);
        name_textfield1.setBounds(58, 104, 262, 33);

        jButton3.setFont(new java.awt.Font("Axure Handwriting", 2, 18)); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(147, 155, 81, 27);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vector-pharmacy.jpg"))); // NOI18N
        jLabel16.setText("jLabel11");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(-30, -10, 980, 340);

        jTabbedPane2.addTab("delete Medicine", jPanel3);

        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel6.setText("name");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 52, 68, 22);

        jLabel7.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel7.setText("price");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 114, 68, 24);

        jLabel8.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel8.setText("amount");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 171, 68, 23);

        jLabel9.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel9.setText("notes");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 231, 68, 25);
        jPanel4.add(price_textfield1);
        price_textfield1.setBounds(88, 114, 155, 34);

        name_textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textfield2ActionPerformed(evt);
            }
        });
        jPanel4.add(name_textfield2);
        name_textfield2.setBounds(88, 45, 155, 36);
        jPanel4.add(amount_textfield1);
        amount_textfield1.setBounds(88, 166, 155, 33);
        jPanel4.add(notes_textfield1);
        notes_textfield1.setBounds(88, 227, 155, 32);

        done_btn2.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        done_btn2.setText("done");
        done_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_btn2ActionPerformed(evt);
            }
        });
        jPanel4.add(done_btn2);
        done_btn2.setBounds(125, 277, 86, 23);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vector-pharmacy.jpg"))); // NOI18N
        jLabel17.setText("jLabel11");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(-30, -10, 980, 340);

        jTabbedPane2.addTab("Update Medicine", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Medicine Managment", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Employee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Axure Handwriting", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel10.setText("name");

        jLabel11.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel11.setText("password");

        jLabel12.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel12.setText("Job rol");

        jButton1.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jButton1.setText("Add ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jButton1))
                        .addComponent(jLabel12)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(55, 55, 55)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(70, 70, 70)
                    .addComponent(jLabel12)
                    .addGap(42, 42, 42)
                    .addComponent(jButton1)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remove Employee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Axure Handwriting", 0, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jLabel13.setText("name");

        jButton2.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(69, 69, 69))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(58, 58, 58)
                .addComponent(jButton2)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Staff management ", jPanel1);

        jTextField4.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButtonsearch.setBackground(new java.awt.Color(0, 204, 255));
        jButtonsearch.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jButtonsearch.setForeground(new java.awt.Color(255, 51, 51));
        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Axure Handwriting", 2, 14)); // NOI18N
        jLabel14.setText("Medicine name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButtonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(36, 36, 36)
                .addComponent(jButtonsearch)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void done_btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String name = name_textfield1.getText();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter the name");
            return;
        }
        Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand=con.createStatement();
            String sql= "delete from medicine where m_name ='" +name+"'";
            int affectedRows = comand.executeUpdate(sql);
            if(affectedRows >= 1)
            {
                JOptionPane.showMessageDialog(this, affectedRows +" medicine 'Successful Deletation !!!' ");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "There is no medicine with that name !!!");
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
                                                
    }                                         

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText();
        String password = jPasswordField1.getText();
        String job_role = jTextField2.getText();
       
        if (name.isEmpty()||password.isEmpty()||job_role.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter all your data");
            return;
        }

        Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand = con.createStatement();
            String sql="select * from employees where name ='"+name+"'";
            rst =comand.executeQuery(sql);
            if(rst.next())
            JOptionPane.showMessageDialog(this, "this name is already Accessed");
            else{
                String query = "INSERT INTO employees VALUES ('"+name+"',"+password+",'"+job_role+"')";

                int affectsRows = comand.executeUpdate(query);
                if(affectsRows == 1)
                {
                    JOptionPane.showMessageDialog(this, "Successful Registration !!!");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error !!!");
                }
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
        String name = jTextField3.getText();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter the name");
            return;
        }
        Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand=con.createStatement();
            String sql= "delete from employees where name ='" +name+"'";
            int affectedRows = comand.executeUpdate(sql);
            if(affectedRows >= 1)
            {
                JOptionPane.showMessageDialog(this, affectedRows +" Employees 'Successful Deletation !!!' ");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "There is no Employee with that name !!!");
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
        // TODO add your handling code here:
        String medicineName=jTextField2.getText();
        if(medicineName.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your a medicine name");
            return;
        }
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        try
        {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "SELECT * FROM medicine where m_name='"+medicineName+"' ";

            result = stmt.executeQuery(query);

            String notes = null;

            if(result.next())
            {
                int amount = result.getInt("amount");
                notes = result.getString("notes");
                if(amount==0) JOptionPane.showMessageDialog(this,"medicine out of stock "+notes);
                else JOptionPane.showMessageDialog(this,"medicine available "+notes);

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid medicine name");
            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        finally
        {
            if(con != null){ try{ con.close();} catch(Exception ex){}}
            if(stmt != null){ try{ stmt.close();} catch(Exception ex){}}
            if(result != null){ try{ result.close();} catch(Exception ex){}}
        }

    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void done_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_btn2ActionPerformed
        String name=name_textfield2.getText();
        System.err.println("ww");
        String am =amount_textfield1.getText();
        int amount=Integer.parseInt(am);
        String notes=notes_textfield1.getText();
        String pr=price_textfield1.getText();
        float price=Float.parseFloat(pr);
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter medicine name");
            return;
        }
        if(am.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please medicine amount");
            return;
        }
        if(notes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter medicine notes");
            return;
        }
        if(pr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter medicine price");
            return;
        }
        Connection con = null;
        Statement comand=null;

        try {

            con= DriverManager.getConnection(url);
            comand = con.createStatement();

            String sql = "UPDATE medicine set notes='"+notes+"',amount= "+amount+",price="+price+ "WHERE m_name='"+name+"'" ;

            int affectsRows = comand.executeUpdate(sql);
            if(affectsRows == 1)
            {
                JOptionPane.showMessageDialog(this, "Successful Update !!!");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Incorrect Id or Old Password !!!");
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            // if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
    }//GEN-LAST:event_done_btn2ActionPerformed

    private void name_textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textfield2ActionPerformed

    private void done_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_btnActionPerformed
        // TODO add your handling code here:
      String name = name_textfield.getText();
        String pr = price_textfield.getText();
        float price = Float.parseFloat(pr);
        String notes = notes_textfield.getText();
        String am = amount_textfield.getText();
        int amount = Integer.parseInt(am);
        if (name.isEmpty()||am.isEmpty()||pr.isEmpty()||notes.isEmpty()
            )
        {
            JOptionPane.showMessageDialog(this, "Please enter all your data");
            return;
        }

        Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand = con.createStatement();
            /*String sql="select * from medicine where m_name ='"+name+"'";
            rst =comand.executeQuery(sql);*/
            
             String query = "INSERT INTO medicine VALUES ('"+name+"','"+amount+"'"
                    + ",'"+notes+"','"+price+"')";


                    
            int affectsRows = comand.executeUpdate(query);
            if(affectsRows == 1)
            {
                JOptionPane.showMessageDialog(this, "Successful Adding !!!");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error !!!");
                    }
            
            
        }
            catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
            
    }//GEN-LAST:event_done_btnActionPerformed

    private void notes_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notes_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notes_textfieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = name_textfield.getText();
        if(name.isEmpty())
        
            {
            JOptionPane.showMessageDialog(this, "Please enter the name");
            return;
        }
      Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand=con.createStatement();
            String sql= "delete from medicine where m_name ='" +name+"'";
             int affectedRows = comand.executeUpdate(sql);
             if(affectedRows >= 1)
             {
                 JOptionPane.showMessageDialog(this, affectedRows +" medicine 'Successful Deletation !!!' ");
             }
             else
             {
                 JOptionPane.showMessageDialog(this, "There is no medicine with that name !!!");
             }
         }

        
        catch(Exception e)
                {
                  JOptionPane.showMessageDialog(this, e.getMessage());  
                }
         finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_textfield;
    private javax.swing.JTextField amount_textfield1;
    private javax.swing.JButton done_btn;
    private javax.swing.JButton done_btn2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JTextField name_textfield1;
    private javax.swing.JTextField name_textfield2;
    private javax.swing.JTextField notes_textfield;
    private javax.swing.JTextField notes_textfield1;
    private javax.swing.JTextField price_textfield;
    private javax.swing.JTextField price_textfield1;
    // End of variables declaration//GEN-END:variables
}
