/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author osama
 */
public class pharmacist extends javax.swing.JFrame {
 private final String url = "jdbc:sqlserver://localhost\\SQL2018;databaseName=pharmacy;user=sa;password=12345;";

    /**
     * Creates new form pharmacist
     */
    public pharmacist() 
    {
        initComponents();
        setVisible(true);
        setResizable(false);
        setLocation(250, 200);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        }catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this,"Cannot Load JDBC Driver !!!");
        }
         
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amount_textfield = new javax.swing.JTextField();
        name_textfield = new javax.swing.JTextField();
        price_textfield = new javax.swing.JTextField();
        notes_textfield = new javax.swing.JTextField();
        done_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        name_textfield1 = new javax.swing.JTextField();
        done_btn1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        price_textfield1 = new javax.swing.JTextField();
        name_textfield2 = new javax.swing.JTextField();
        amount_textfield1 = new javax.swing.JTextField();
        notes_textfield1 = new javax.swing.JTextField();
        done_btn2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButtonsearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("amount");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 140, 70, 26);

        jLabel1.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 31, 70, 26);

        jLabel2.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("price");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 91, 70, 25);

        jLabel4.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("notes");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 200, 50, 24);

        amount_textfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amount_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_textfieldActionPerformed(evt);
            }
        });
        jPanel2.add(amount_textfield);
        amount_textfield.setBounds(80, 140, 170, 31);

        name_textfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(name_textfield);
        name_textfield.setBounds(81, 34, 170, 35);

        price_textfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(price_textfield);
        price_textfield.setBounds(81, 87, 170, 32);

        notes_textfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(notes_textfield);
        notes_textfield.setBounds(80, 190, 170, 32);

        done_btn.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        done_btn.setText("done");
        done_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_btnActionPerformed(evt);
            }
        });
        jPanel2.add(done_btn);
        done_btn.setBounds(120, 250, 90, 27);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vector-pharmacy.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(-30, -10, 980, 340);

        jTabbedPane1.addTab("Add", jPanel2);

        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Medicine Name");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(80, 60, 155, 24);
        jPanel3.add(name_textfield1);
        name_textfield1.setBounds(27, 94, 262, 33);

        done_btn1.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        done_btn1.setText("done");
        done_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(done_btn1);
        done_btn1.setBounds(108, 145, 90, 36);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vector-pharmacy.jpg"))); // NOI18N
        jLabel13.setText("jLabel11");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(-30, -10, 980, 340);

        jTabbedPane1.addTab("delete", jPanel3);

        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("name");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 45, 68, 22);

        jLabel7.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("price");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 85, 68, 24);

        jLabel8.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("amount");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 130, 68, 23);

        jLabel9.setFont(new java.awt.Font("Axure Handwriting", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("notes");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 176, 68, 25);

        price_textfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_textfield1ActionPerformed(evt);
            }
        });
        jPanel4.add(price_textfield1);
        price_textfield1.setBounds(88, 85, 145, 24);

        name_textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textfield2ActionPerformed(evt);
            }
        });
        jPanel4.add(name_textfield2);
        name_textfield2.setBounds(88, 45, 145, 22);
        jPanel4.add(amount_textfield1);
        amount_textfield1.setBounds(90, 130, 145, 23);
        jPanel4.add(notes_textfield1);
        notes_textfield1.setBounds(90, 170, 145, 25);

        done_btn2.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        done_btn2.setText("done");
        done_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_btn2ActionPerformed(evt);
            }
        });
        jPanel4.add(done_btn2);
        done_btn2.setBounds(122, 219, 79, 33);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vector-pharmacy.jpg"))); // NOI18N
        jLabel14.setText("jLabel11");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(-30, -10, 980, 340);

        jTabbedPane1.addTab("Update", jPanel4);

        jPanel1.setLayout(null);

        jTextField2.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(141, 118, 268, 40);

        jButtonsearch.setBackground(new java.awt.Color(0, 204, 255));
        jButtonsearch.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jButtonsearch.setForeground(new java.awt.Color(255, 51, 51));
        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsearch);
        jButtonsearch.setBounds(220, 180, 90, 23);

        jLabel10.setFont(new java.awt.Font("Axure Handwriting", 3, 14)); // NOI18N
        jLabel10.setText("Medicine name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(36, 130, 110, 15);

        jLabel15.setIcon(new javax.swing.ImageIcon("F:\\Pharmacy system (3) (1)\\Pharmacy system (3)\\Pharmacy system\\src\\pharmacy\\46257_2aa2_9.jpg")); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(-110, -60, 680, 460);

        jTabbedPane1.addTab("Search", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void done_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_btnActionPerformed
        // TODO add your handling code here:
        String name = name_textfield.getText();
        String pr = price_textfield.getText();
        float price = Float.parseFloat(pr);
        String notes = notes_textfield.getText();
        String am = amount_textfield.getText();
        int amount = Integer.parseInt(am);
        if (name.isEmpty()||am.isEmpty()||pr.isEmpty()||notes.isEmpty()
            )
        {
            JOptionPane.showMessageDialog(this, "Please enter all your data");
            return;
        }

        Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand = con.createStatement();
            /*String sql="select * from medicine where m_name ='"+name+"'";
            rst =comand.executeQuery(sql);*/
            
             String query = "INSERT INTO medicine VALUES ('"+name+"','"+amount+"'"
                    + ",'"+notes+"','"+price+"')";


                    
            int affectsRows = comand.executeUpdate(query);
            if(affectsRows == 1)
            {
                JOptionPane.showMessageDialog(this, "Successful Adding !!!");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error !!!");
                    }
            
            
        }
            catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
               
    }//GEN-LAST:event_done_btnActionPerformed

    private void name_textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textfield2ActionPerformed

    private void done_btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String name = name_textfield1.getText();
        if(name.isEmpty())
        
            {
            JOptionPane.showMessageDialog(this, "Please enter the name");
            return;
        }
      Connection con = null;
        Statement comand=null;
        ResultSet rst = null;
        try {

            con= DriverManager.getConnection(url);
            comand=con.createStatement();
            String sql= "delete from medicine where m_name ='" +name+"'";
             int affectedRows = comand.executeUpdate(sql);
             if(affectedRows >= 1)
             {
                 JOptionPane.showMessageDialog(this, affectedRows +" medicine 'Successful Deletation !!!' ");
             }
             else
             {
                 JOptionPane.showMessageDialog(this, "There is no medicine with that name !!!");
             }
         }

        
        catch(Exception e)
                {
                  JOptionPane.showMessageDialog(this, e.getMessage());  
                }
         finally{
            if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
                                            

    }                                         

    private void done_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_btn2ActionPerformed
        String name=name_textfield2.getText();
        System.err.println("ww");
        String am =amount_textfield1.getText();
        int amount=Integer.parseInt(am);
        String notes=notes_textfield1.getText();
        String pr=price_textfield1.getText();
        float price=Float.parseFloat(pr);
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter medicine name");
            return;
        }
        if(am.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please medicine amount");
            return;
        }
        if(notes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter medicine notes");
            return;
        }
        if(pr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter medicine price");
            return;
        }
        Connection con = null;
        Statement comand=null;
        
        try {

            con= DriverManager.getConnection(url);
            comand = con.createStatement();
            
            
                
               String sql = "UPDATE medicine set notes='"+notes+"',amount= "+amount+",price="+price+ "WHERE m_name='"+name+"'" ;
                                
                
                int affectsRows = comand.executeUpdate(sql);
            if(affectsRows == 1)
            {
                JOptionPane.showMessageDialog(this, "Successful Update !!!");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Incorrect Id or Old Password !!!");
            }

            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
           // if(rst!=null) try{rst.close();}catch(Exception e){}
            if(con!=null) try{con.close();}catch(Exception e){}
            if(comand!=null) try{comand.close();}catch(Exception e){}
        }
    }//GEN-LAST:event_done_btn2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
        // TODO add your handling code here:
        String medicineName=jTextField2.getText();
        if(medicineName.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your a medicine name");
            return;
        }
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        try
        {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "SELECT * FROM medicine where m_name='"+medicineName+"' ";

            result = stmt.executeQuery(query);

            String notes = null;

            if(result.next())
            {
                int amount = result.getInt("amount");
                notes = result.getString("notes");
                if(amount==0) JOptionPane.showMessageDialog(this,"medicine out of stock "+notes);
                else JOptionPane.showMessageDialog(this,"medicine available "+notes);

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid medicine name");
            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        finally
        {
            if(con != null){ try{ con.close();} catch(Exception ex){}}
            if(stmt != null){ try{ stmt.close();} catch(Exception ex){}}
            if(result != null){ try{ result.close();} catch(Exception ex){}}
        }
                  
    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void amount_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_textfieldActionPerformed

    private void price_textfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_textfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_textfield1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pharmacist().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_textfield;
    private javax.swing.JTextField amount_textfield1;
    private javax.swing.JButton done_btn;
    private javax.swing.JButton done_btn1;
    private javax.swing.JButton done_btn2;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JTextField name_textfield1;
    private javax.swing.JTextField name_textfield2;
    private javax.swing.JTextField notes_textfield;
    private javax.swing.JTextField notes_textfield1;
    private javax.swing.JTextField price_textfield;
    private javax.swing.JTextField price_textfield1;
    // End of variables declaration//GEN-END:variables
}
