/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author M.A.S tech
 */
public class search_page extends javax.swing.JFrame {
     private final String url = "jdbc:sqlserver://localhost\\SQL2018;databaseName=pharmacy;user=sa;password=12345;";

    /**
     * Creates new form search_page
     */
    public search_page() {
        initComponents();
    }

    search_page(String firstname,String lastname) 
    {
        initComponents();
        jLabel1.setText("wellcome  "+firstname+"  "+lastname);
        setVisible(true);
        setLocation(190, 180);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        setResizable(false);
         try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        }catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this,"Cannot Load JDBC Driver !!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonsearch = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buy_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 178, 30);

        jButtonsearch.setBackground(new java.awt.Color(0, 204, 255));
        jButtonsearch.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        jButtonsearch.setForeground(new java.awt.Color(255, 51, 51));
        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsearch);
        jButtonsearch.setBounds(390, 250, 90, 23);

        SearchTextField.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(153, 153, 153));
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(SearchTextField);
        SearchTextField.setBounds(187, 188, 370, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("هذا المشروع قيد التطوير");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 370, 170, 14);

        buy_button.setBackground(new java.awt.Color(0, 204, 204));
        buy_button.setFont(new java.awt.Font("Axure Handwriting", 1, 14)); // NOI18N
        buy_button.setForeground(new java.awt.Color(255, 0, 0));
        buy_button.setText("Buy ");
        buy_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(buy_button);
        buy_button.setBounds(250, 250, 100, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\Pharmacy system (3) (1)\\Pharmacy system (3)\\Pharmacy system\\src\\pharmacy\\46257_2aa2_9.jpg")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, -20, 680, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
        // TODO add your handling code here:
        String medicineName=SearchTextField.getText();
        if(medicineName.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your a medicine name");
            return;
        }
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        try
        {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "SELECT * FROM medicine where m_name='"+medicineName+"' ";

            result = stmt.executeQuery(query);

            String notes = null;

            if(result.next())
            {
                int amount = result.getInt("amount");
                notes = result.getString("notes");
                if(amount==0) JOptionPane.showMessageDialog(this,"medicine out of stock "+notes);
                else JOptionPane.showMessageDialog(this,"medicine available "+notes);

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid medicine name");
            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        finally
        {
            if(con != null){ try{ con.close();} catch(Exception ex){}}
            if(stmt != null){ try{ stmt.close();} catch(Exception ex){}}
            if(result != null){ try{ result.close();} catch(Exception ex){}}
        }
    }//GEN-LAST:event_jButtonsearchActionPerformed
    String m_name = null;
    private void buy_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_buttonActionPerformed
        // TODO add your handling code here:
        
        m_name = SearchTextField.getText();
        Buy b=new Buy(m_name);
       
    }//GEN-LAST:event_buy_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField SearchTextField;
    private javax.swing.JButton buy_button;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
